 const data = [
    {
      "code": "DCOC",
      "name": "Deliverable Cocoa",
      "board": {
        "code": "S",
        "name": "Spot"
      },
      "board_code": "S",
      "commodity_code": "CCO",
      "location_basis_code": "",
      "created": "2021-09-21T05:10:02.710529Z",
      "commodity_image_url": "",
      "is_virtual_security": false,
      "volume_per_unit": 1000,
      "security_type": "Dawa",
      "season_to_date_change": -100,
      "best_buy": 0,
      "best_sell": 0,
      "no_of_deals": 0,
      "daily_change": 0,
      "can_be_bought": true,
      "can_be_sold": true,
      "show_on_demo": true,
      "show_on_live": true,
      "use_ecn_fees": true
    },
    {
      "code": "DCSN",
      "name": "Deliverable Cashew Nuts",
      "board": {
        "code": "S",
        "name": "Spot"
      },
      "board_code": "S",
      "commodity_code": "CSN",
      "location_basis_code": "",
      "created": "2021-10-21T05:10:01.396947Z",
      "commodity_image_url": "",
      "is_virtual_security": false,
      "volume_per_unit": 1000,
      "security_type": "Dawa",
      "season_to_date_change": -100,
      "best_buy": 0,
      "best_sell": 0,
      "no_of_deals": 0,
      "daily_change": 0,
      "can_be_bought": true,
      "can_be_sold": true,
      "show_on_demo": true,
      "show_on_live": true,
      "use_ecn_fees": true
    },
    {
      "code": "DGNG",
      "name": "Deliverable Ginger Dried Split",
      "board": {
        "code": "S",
        "name": "Spot"
      },
      "board_code": "S",
      "commodity_code": "GNG",
      "location_basis_code": "",
      "created": "2021-10-21T05:10:01.406722Z",
      "commodity_image_url": "",
      "is_virtual_security": false,
      "volume_per_unit": 1000,
      "security_type": "Dawa",
      "season_to_date_change": 0,
      "best_buy": 0,
      "best_sell": 0,
      "no_of_deals": 0,
      "daily_change": 0,
      "can_be_bought": true,
      "can_be_sold": true,
      "show_on_demo": true,
      "show_on_live": true,
      "use_ecn_fees": true
    },
    {
      "code": "SMAZ",
      "name": "Maize",
      "board": {
        "code": "S",
        "name": "Spot"
      },
      "board_code": "S",
      "commodity_code": "MAZ",
      "location_basis_code": "321",
      "created": "2021-04-26T05:52:38.135484Z",
      "commodity_image_url": "/media/products/Paddy_Rice_in_a_pod_i8KpNhT.jpeg",
      "is_virtual_security": false,
      "volume_per_unit": 1,
      "security_type": "Spot",
      "season_to_date_change": -100,
      "best_buy": 0,
      "best_sell": 150,
      "no_of_deals": 198,
      "daily_change": 0,
      "can_be_bought": true,
      "can_be_sold": true,
      "show_on_demo": true,
      "show_on_live": true,
      "use_ecn_fees": true
    },
    {
      "code": "OCOC",
      "name": "Cocoa",
      "board": {
        "code": "O",
        "name": "OTC"
      },
      "board_code": "O",
      "commodity_code": "CCO",
      "location_basis_code": "",
      "created": "2021-05-04T06:25:51.166303Z",
      "commodity_image_url": "",
      "is_virtual_security": false,
      "volume_per_unit": 1,
      "security_type": "Spot",
      "season_to_date_change": 0,
      "best_buy": 0,
      "best_sell": 0,
      "no_of_deals": 0,
      "daily_change": 0,
      "can_be_bought": true,
      "can_be_sold": true,
      "show_on_demo": true,
      "show_on_live": true,
      "use_ecn_fees": true
    },
    {
      "code": "OPRL",
      "name": "Paddy Rice Long Grain",
      "board": {
        "code": "O",
        "name": "OTC"
      },
      "board_code": "O",
      "commodity_code": "PRL",
      "location_basis_code": "",
      "created": "2021-04-26T05:52:38.158959Z",
      "commodity_image_url": "/media/products/Paddy_Rice_in_a_pod_VJ3ngSA.jpeg",
      "is_virtual_security": false,
      "volume_per_unit": 1,
      "security_type": "Spot",
      "season_to_date_change": -100,
      "best_buy": 0,
      "best_sell": 0,
      "no_of_deals": 0,
      "daily_change": 0,
      "can_be_bought": true,
      "can_be_sold": true,
      "show_on_demo": true,
      "show_on_live": true,
      "use_ecn_fees": true
    },
    {
      "code": "OSGM",
      "name": "Sorghum",
      "board": {
        "code": "O",
        "name": "OTC"
      },
      "board_code": "O",
      "commodity_code": "SGM",
      "location_basis_code": "",
      "created": "2021-04-26T05:52:38.172516Z",
      "commodity_image_url": "/media/products/Soybean_UrbYV2U.jpeg",
      "is_virtual_security": false,
      "volume_per_unit": 1,
      "security_type": "Spot",
      "season_to_date_change": 0,
      "best_buy": 0,
      "best_sell": 0,
      "no_of_deals": 0,
      "daily_change": 0,
      "can_be_bought": true,
      "can_be_sold": true,
      "show_on_demo": true,
      "show_on_live": true,
      "use_ecn_fees": true
    },
    {
      "code": "OSBS",
      "name": "Soybean",
      "board": {
        "code": "O",
        "name": "OTC"
      },
      "board_code": "O",
      "commodity_code": "SBS",
      "location_basis_code": "",
      "created": "2021-04-26T05:52:38.185958Z",
      "commodity_image_url": "/media/products/Soybeans_main_IcPIJJv.jpeg",
      "is_virtual_security": false,
      "volume_per_unit": 1,
      "security_type": "Spot",
      "season_to_date_change": -100,
      "best_buy": 0,
      "best_sell": 0,
      "no_of_deals": 0,
      "daily_change": 0,
      "can_be_bought": true,
      "can_be_sold": true,
      "show_on_demo": true,
      "show_on_live": true,
      "use_ecn_fees": true
    },
    {
      "code": "VGNG",
      "name": "Ginger Vertual",
      "board": {
        "code": "V",
        "name": "Virtual"
      },
      "board_code": "V",
      "commodity_code": "GNG",
      "location_basis_code": "",
      "created": "2021-05-04T06:25:52.488148Z",
      "commodity_image_url": "",
      "is_virtual_security": true,
      "volume_per_unit": 1,
      "security_type": "Spot",
      "season_to_date_change": 0,
      "best_buy": 0,
      "best_sell": 0,
      "no_of_deals": 0,
      "daily_change": 0,
      "can_be_bought": true,
      "can_be_sold": true,
      "show_on_demo": true,
      "show_on_live": true,
      "use_ecn_fees": true
    },
    {
      "code": "OGNG",
      "name": "Ginger",
      "board": {
        "code": "O",
        "name": "OTC"
      },
      "board_code": "O",
      "commodity_code": "GNG",
      "location_basis_code": "",
      "created": "2021-05-04T06:25:52.495312Z",
      "commodity_image_url": "",
      "is_virtual_security": false,
      "volume_per_unit": 1,
      "security_type": "Spot",
      "season_to_date_change": 0,
      "best_buy": 0,
      "best_sell": 0,
      "no_of_deals": 0,
      "daily_change": 0,
      "can_be_bought": true,
      "can_be_sold": true,
      "show_on_demo": true,
      "show_on_live": true,
      "use_ecn_fees": true
    },
    {
      "code": "GMAZ",
      "name": "SCIT Maize",
      "board": {
        "code": "G",
        "name": "SCIT"
      },
      "board_code": "G",
      "commodity_code": "MAZ",
      "location_basis_code": "321",
      "created": "2021-05-04T06:25:52.503012Z",
      "commodity_image_url": "/media/products/Paddy_Rice_in_a_pod_i8KpNhT.jpeg",
      "is_virtual_security": false,
      "volume_per_unit": 1,
      "security_type": "Spot",
      "season_to_date_change": 0,
      "best_buy": 0,
      "best_sell": 0,
      "no_of_deals": 0,
      "daily_change": 0,
      "can_be_bought": true,
      "can_be_sold": true,
      "show_on_demo": true,
      "show_on_live": true,
      "use_ecn_fees": true
    },
    {
      "code": "DMAZ",
      "name": "Deliverable Maize",
      "board": {
        "code": "S",
        "name": "Spot"
      },
      "board_code": "S",
      "commodity_code": "MAZ",
      "location_basis_code": "321",
      "created": "2021-08-03T13:44:50.150899Z",
      "commodity_image_url": "/media/products/Paddy_Rice_in_a_pod_i8KpNhT.jpeg",
      "is_virtual_security": false,
      "volume_per_unit": 1000,
      "security_type": "Dawa",
      "season_to_date_change": -99.68,
      "best_buy": 0,
      "best_sell": 3000,
      "no_of_deals": 26,
      "daily_change": -66837.5,
      "can_be_bought": true,
      "can_be_sold": true,
      "show_on_demo": true,
      "show_on_live": true,
      "use_ecn_fees": true
    },
    {
      "code": "TMAZ",
      "name": "Maize",
      "board": {
        "code": "G",
        "name": "SCIT"
      },
      "board_code": "G",
      "commodity_code": "TMAZ",
      "location_basis_code": "",
      "created": "2021-05-04T06:25:52.786591Z",
      "commodity_image_url": "",
      "is_virtual_security": false,
      "volume_per_unit": 1,
      "security_type": "Spot",
      "season_to_date_change": 0,
      "best_buy": 0,
      "best_sell": 0,
      "no_of_deals": 0,
      "daily_change": 0,
      "can_be_bought": true,
      "can_be_sold": true,
      "show_on_demo": true,
      "show_on_live": true,
      "use_ecn_fees": false
    },
    {
      "code": "OCSN",
      "name": "Cashew Nuts",
      "board": {
        "code": "O",
        "name": "OTC"
      },
      "board_code": "O",
      "commodity_code": "CSN",
      "location_basis_code": "",
      "created": "2021-05-04T06:25:52.799308Z",
      "commodity_image_url": "",
      "is_virtual_security": false,
      "volume_per_unit": 1,
      "security_type": "Spot",
      "season_to_date_change": 0,
      "best_buy": 0,
      "best_sell": 0,
      "no_of_deals": 0,
      "daily_change": 100,
      "can_be_bought": true,
      "can_be_sold": true,
      "show_on_demo": true,
      "show_on_live": true,
      "use_ecn_fees": false
    },
    {
      "code": "DSBS",
      "name": "Deliverable Soyabean",
      "board": {
        "code": "S",
        "name": "Spot"
      },
      "board_code": "S",
      "commodity_code": "SBS",
      "location_basis_code": "",
      "created": "2021-09-08T12:48:27.570156Z",
      "commodity_image_url": "/media/products/Soybeans_main_IcPIJJv.jpeg",
      "is_virtual_security": false,
      "volume_per_unit": 1000,
      "security_type": "Dawa",
      "season_to_date_change": 133.33,
      "best_buy": 0,
      "best_sell": 0,
      "no_of_deals": 0,
      "daily_change": 57.14,
      "can_be_bought": true,
      "can_be_sold": true,
      "show_on_demo": true,
      "show_on_live": true,
      "use_ecn_fees": true
    },
    {
      "code": "OMAZ",
      "name": "Maize",
      "board": {
        "code": "O",
        "name": "OTC"
      },
      "board_code": "O",
      "commodity_code": "MAZ",
      "location_basis_code": "321",
      "created": "2021-04-26T05:52:38.145541Z",
      "commodity_image_url": "/media/products/Paddy_Rice_in_a_pod_i8KpNhT.jpeg",
      "is_virtual_security": false,
      "volume_per_unit": 1000,
      "security_type": "Spot",
      "season_to_date_change": -100,
      "best_buy": 0,
      "best_sell": 215000,
      "no_of_deals": 8,
      "daily_change": 0,
      "can_be_bought": true,
      "can_be_sold": true,
      "show_on_demo": true,
      "show_on_live": true,
      "use_ecn_fees": true
    },
    {
      "code": "SSBS",
      "name": "Soybean",
      "board": {
        "code": "S",
        "name": "Spot"
      },
      "board_code": "S",
      "commodity_code": "SBS",
      "location_basis_code": "",
      "created": "2021-04-26T05:52:38.179298Z",
      "commodity_image_url": "/media/products/Soybeans_main_IcPIJJv.jpeg",
      "is_virtual_security": false,
      "volume_per_unit": 1,
      "security_type": "Spot",
      "season_to_date_change": -100,
      "best_buy": 0,
      "best_sell": 150,
      "no_of_deals": 5,
      "daily_change": 0,
      "can_be_bought": true,
      "can_be_sold": true,
      "show_on_demo": true,
      "show_on_live": true,
      "use_ecn_fees": true
    },
    {
      "code": "SSGM",
      "name": "Sorghum",
      "board": {
        "code": "S",
        "name": "Spot"
      },
      "board_code": "S",
      "commodity_code": "SGM",
      "location_basis_code": "",
      "created": "2021-04-26T05:52:38.165936Z",
      "commodity_image_url": "/media/products/Soybean_UrbYV2U.jpeg",
      "is_virtual_security": false,
      "volume_per_unit": 1,
      "security_type": "Spot",
      "season_to_date_change": -100,
      "best_buy": 0,
      "best_sell": 180,
      "no_of_deals": 0,
      "daily_change": 0,
      "can_be_bought": true,
      "can_be_sold": true,
      "show_on_demo": true,
      "show_on_live": true,
      "use_ecn_fees": true
    },
    {
      "code": "SPRL",
      "name": "Paddy Rice",
      "board": {
        "code": "S",
        "name": "Spot"
      },
      "board_code": "S",
      "commodity_code": "PRL",
      "location_basis_code": "",
      "created": "2021-04-26T05:52:38.152622Z",
      "commodity_image_url": "/media/products/Paddy_Rice_in_a_pod_VJ3ngSA.jpeg",
      "is_virtual_security": false,
      "volume_per_unit": 1,
      "security_type": "Spot",
      "season_to_date_change": 0,
      "best_buy": 0,
      "best_sell": 0,
      "no_of_deals": 0,
      "daily_change": 0,
      "can_be_bought": true,
      "can_be_sold": true,
      "show_on_demo": true,
      "show_on_live": true,
      "use_ecn_fees": true
    },
    {
      "code": "CGNG",
      "name": "Ginger (Export Grade).",
      "board": {
        "code": "C",
        "name": "Export Contract"
      },
      "board_code": "C",
      "commodity_code": "CGNG",
      "location_basis_code": "",
      "created": "2021-05-03T05:10:02.267116Z",
      "commodity_image_url": "",
      "is_virtual_security": false,
      "volume_per_unit": 1,
      "security_type": "Spot",
      "season_to_date_change": 0,
      "best_buy": 0,
      "best_sell": 0,
      "no_of_deals": 0,
      "daily_change": 0,
      "can_be_bought": true,
      "can_be_sold": true,
      "show_on_demo": true,
      "show_on_live": true,
      "use_ecn_fees": false
    },
    {
      "code": "FETC",
      "name": "Fair Trade ETC",
      "board": {
        "code": "S",
        "name": "Spot"
      },
      "board_code": "S",
      "commodity_code": "FETC",
      "location_basis_code": "",
      "created": "2021-05-04T06:25:49.935373Z",
      "commodity_image_url": "",
      "is_virtual_security": false,
      "volume_per_unit": 1,
      "security_type": "Spot",
      "season_to_date_change": 0,
      "best_buy": 0,
      "best_sell": 0,
      "no_of_deals": 0,
      "daily_change": 0,
      "can_be_bought": true,
      "can_be_sold": true,
      "show_on_demo": true,
      "show_on_live": true,
      "use_ecn_fees": true
    },
    {
      "code": "VCOC",
      "name": "Cocoa Virt",
      "board": {
        "code": "V",
        "name": "Virtual"
      },
      "board_code": "V",
      "commodity_code": "CCO",
      "location_basis_code": "",
      "created": "2021-05-04T06:25:49.956196Z",
      "commodity_image_url": "",
      "is_virtual_security": true,
      "volume_per_unit": 1,
      "security_type": "Spot",
      "season_to_date_change": 0,
      "best_buy": 0,
      "best_sell": 0,
      "no_of_deals": 0,
      "daily_change": 0,
      "can_be_bought": true,
      "can_be_sold": true,
      "show_on_demo": true,
      "show_on_live": true,
      "use_ecn_fees": true
    },
    {
      "code": "VSBS",
      "name": "Virtual Soybean",
      "board": {
        "code": "V",
        "name": "Virtual"
      },
      "board_code": "V",
      "commodity_code": "SBS",
      "location_basis_code": "",
      "created": "2021-05-04T06:25:49.962310Z",
      "commodity_image_url": "/media/products/Soybeans_main_IcPIJJv.jpeg",
      "is_virtual_security": true,
      "volume_per_unit": 1,
      "security_type": "Spot",
      "season_to_date_change": 0,
      "best_buy": 0,
      "best_sell": 0,
      "no_of_deals": 0,
      "daily_change": 0,
      "can_be_bought": true,
      "can_be_sold": true,
      "show_on_demo": true,
      "show_on_live": true,
      "use_ecn_fees": true
    },
    {
      "code": "VSGM",
      "name": "Virtual Sorghum",
      "board": {
        "code": "V",
        "name": "Virtual"
      },
      "board_code": "V",
      "commodity_code": "SGM",
      "location_basis_code": "",
      "created": "2021-05-04T06:25:50.267447Z",
      "commodity_image_url": "/media/products/Soybean_UrbYV2U.jpeg",
      "is_virtual_security": true,
      "volume_per_unit": 1,
      "security_type": "Spot",
      "season_to_date_change": 0,
      "best_buy": 0,
      "best_sell": 0,
      "no_of_deals": 0,
      "daily_change": 0,
      "can_be_bought": true,
      "can_be_sold": true,
      "show_on_demo": true,
      "show_on_live": true,
      "use_ecn_fees": true
    },
    {
      "code": "VPRL",
      "name": "Virtual Paddy Rice",
      "board": {
        "code": "V",
        "name": "Virtual"
      },
      "board_code": "V",
      "commodity_code": "PRL",
      "location_basis_code": "",
      "created": "2021-05-04T06:25:50.546382Z",
      "commodity_image_url": "/media/products/Paddy_Rice_in_a_pod_VJ3ngSA.jpeg",
      "is_virtual_security": true,
      "volume_per_unit": 1,
      "security_type": "Spot",
      "season_to_date_change": 0,
      "best_buy": 0,
      "best_sell": 0,
      "no_of_deals": 0,
      "daily_change": 0,
      "can_be_bought": true,
      "can_be_sold": true,
      "show_on_demo": true,
      "show_on_live": true,
      "use_ecn_fees": true
    },
    {
      "code": "VMAZ",
      "name": "Virtual Maize",
      "board": {
        "code": "V",
        "name": "Virtual"
      },
      "board_code": "V",
      "commodity_code": "MAZ",
      "location_basis_code": "321",
      "created": "2021-05-04T06:25:50.859644Z",
      "commodity_image_url": "/media/products/Paddy_Rice_in_a_pod_i8KpNhT.jpeg",
      "is_virtual_security": true,
      "volume_per_unit": 1,
      "security_type": "Spot",
      "season_to_date_change": 0,
      "best_buy": 0,
      "best_sell": 0,
      "no_of_deals": 0,
      "daily_change": 0,
      "can_be_bought": true,
      "can_be_sold": true,
      "show_on_demo": true,
      "show_on_live": true,
      "use_ecn_fees": true
    },
    {
      "code": "VSSM",
      "name": "Sesame Virtual",
      "board": {
        "code": "V",
        "name": "Virtual"
      },
      "board_code": "V",
      "commodity_code": "SSM",
      "location_basis_code": "",
      "created": "2021-05-04T06:25:51.153242Z",
      "commodity_image_url": "",
      "is_virtual_security": true,
      "volume_per_unit": 1,
      "security_type": "Spot",
      "season_to_date_change": 0,
      "best_buy": 0,
      "best_sell": 0,
      "no_of_deals": 0,
      "daily_change": 0,
      "can_be_bought": true,
      "can_be_sold": true,
      "show_on_demo": true,
      "show_on_live": true,
      "use_ecn_fees": true
    },
    {
      "code": "OSSM",
      "name": "Sesame",
      "board": {
        "code": "O",
        "name": "OTC"
      },
      "board_code": "O",
      "commodity_code": "SSM",
      "location_basis_code": "",
      "created": "2021-05-04T06:25:51.159594Z",
      "commodity_image_url": "",
      "is_virtual_security": false,
      "volume_per_unit": 1,
      "security_type": "Spot",
      "season_to_date_change": 0,
      "best_buy": 0,
      "best_sell": 0,
      "no_of_deals": 0,
      "daily_change": 0,
      "can_be_bought": true,
      "can_be_sold": true,
      "show_on_demo": true,
      "show_on_live": true,
      "use_ecn_fees": true
    },
    {
      "code": "SCOC",
      "name": "Cocoa",
      "board": {
        "code": "S",
        "name": "Spot"
      },
      "board_code": "S",
      "commodity_code": "CCO",
      "location_basis_code": "",
      "created": "2021-05-04T06:25:49.928578Z",
      "commodity_image_url": "",
      "is_virtual_security": false,
      "volume_per_unit": 1,
      "security_type": "Spot",
      "season_to_date_change": -100,
      "best_buy": 0,
      "best_sell": 1200.29,
      "no_of_deals": 0,
      "daily_change": 0,
      "can_be_bought": true,
      "can_be_sold": true,
      "show_on_demo": true,
      "show_on_live": true,
      "use_ecn_fees": true
    },
    {
      "code": "SCSN",
      "name": "Spot Cashew Nuts",
      "board": {
        "code": "S",
        "name": "Spot"
      },
      "board_code": "S",
      "commodity_code": "CSN",
      "location_basis_code": "",
      "created": "2021-05-04T06:25:52.793221Z",
      "commodity_image_url": "",
      "is_virtual_security": false,
      "volume_per_unit": 1,
      "security_type": "Spot",
      "season_to_date_change": 0,
      "best_buy": 0,
      "best_sell": 0,
      "no_of_deals": 0,
      "daily_change": 0,
      "can_be_bought": true,
      "can_be_sold": true,
      "show_on_demo": true,
      "show_on_live": true,
      "use_ecn_fees": true
    },
    {
      "code": "AFIN",
      "name": "AFEX Input Note",
      "board": {
        "code": "S",
        "name": "Spot"
      },
      "board_code": "S",
      "commodity_code": "AFIN",
      "location_basis_code": "",
      "created": "2021-05-04T06:25:49.949847Z",
      "commodity_image_url": "",
      "is_virtual_security": false,
      "volume_per_unit": 1,
      "security_type": "FI",
      "season_to_date_change": -100,
      "best_buy": 0,
      "best_sell": 0,
      "no_of_deals": 0,
      "daily_change": 0,
      "can_be_bought": true,
      "can_be_sold": true,
      "show_on_demo": true,
      "show_on_live": true,
      "use_ecn_fees": false
    },
    {
      "code": "ABCP",
      "name": "Asset Backed Commercial Paper",
      "board": {
        "code": "S",
        "name": "Spot"
      },
      "board_code": "S",
      "commodity_code": "ABCP",
      "location_basis_code": "",
      "created": "2021-05-04T06:25:49.942446Z",
      "commodity_image_url": "",
      "is_virtual_security": false,
      "volume_per_unit": 1,
      "security_type": "FI",
      "season_to_date_change": 0,
      "best_buy": 0,
      "best_sell": 0,
      "no_of_deals": 0,
      "daily_change": 0,
      "can_be_bought": false,
      "can_be_sold": false,
      "show_on_demo": true,
      "show_on_live": false,
      "use_ecn_fees": false
    },
    {
      "code": "CEXP",
      "name": "Export Note",
      "board": {
        "code": "S",
        "name": "Spot"
      },
      "board_code": "S",
      "commodity_code": "CEXP",
      "location_basis_code": "",
      "created": "2021-05-04T06:25:49.627382Z",
      "commodity_image_url": "",
      "is_virtual_security": false,
      "volume_per_unit": 1,
      "security_type": "FI",
      "season_to_date_change": 0,
      "best_buy": 0,
      "best_sell": 0,
      "no_of_deals": 0,
      "daily_change": 0,
      "can_be_bought": false,
      "can_be_sold": false,
      "show_on_demo": true,
      "show_on_live": false,
      "use_ecn_fees": false
    },
    {
      "code": "NPRL-E",
      "name": "Paddy Rice Aggregation Note Ehtical",
      "board": {
        "code": "S",
        "name": "Spot"
      },
      "board_code": "S",
      "commodity_code": "NPRL-E",
      "location_basis_code": "",
      "created": "2021-05-04T06:25:49.621037Z",
      "commodity_image_url": "",
      "is_virtual_security": false,
      "volume_per_unit": 1,
      "security_type": "FI",
      "season_to_date_change": 0,
      "best_buy": 0,
      "best_sell": 0,
      "no_of_deals": 0,
      "daily_change": 0,
      "can_be_bought": false,
      "can_be_sold": false,
      "show_on_demo": true,
      "show_on_live": false,
      "use_ecn_fees": false
    },
    {
      "code": "NPRL",
      "name": "Paddy Rice Aggregation Note",
      "board": {
        "code": "S",
        "name": "Spot"
      },
      "board_code": "S",
      "commodity_code": "NPRL",
      "location_basis_code": "",
      "created": "2021-05-04T06:25:49.612725Z",
      "commodity_image_url": "",
      "is_virtual_security": false,
      "volume_per_unit": 1,
      "security_type": "FI",
      "season_to_date_change": 0,
      "best_buy": 0,
      "best_sell": 0,
      "no_of_deals": 0,
      "daily_change": 0,
      "can_be_bought": false,
      "can_be_sold": false,
      "show_on_demo": true,
      "show_on_live": false,
      "use_ecn_fees": false
    },
    {
      "code": "DPRL",
      "name": "Deliverable Paddy Rice Long Grain",
      "board": {
        "code": "S",
        "name": "Spot"
      },
      "board_code": "S",
      "commodity_code": "PRL",
      "location_basis_code": "",
      "created": "2021-10-21T05:10:01.324446Z",
      "commodity_image_url": "/media/products/Paddy_Rice_in_a_pod_VJ3ngSA.jpeg",
      "is_virtual_security": false,
      "volume_per_unit": 1000,
      "security_type": "Dawa",
      "season_to_date_change": 0,
      "best_buy": 0,
      "best_sell": 0,
      "no_of_deals": 0,
      "daily_change": 0,
      "can_be_bought": true,
      "can_be_sold": true,
      "show_on_demo": true,
      "show_on_live": true,
      "use_ecn_fees": true
    },
    {
      "code": "DSSM",
      "name": "Deliverable Sesame Seed",
      "board": {
        "code": "S",
        "name": "Spot"
      },
      "board_code": "S",
      "commodity_code": "SSM",
      "location_basis_code": "",
      "created": "2021-10-21T05:10:01.341615Z",
      "commodity_image_url": "",
      "is_virtual_security": false,
      "volume_per_unit": 1000,
      "security_type": "Dawa",
      "season_to_date_change": 0,
      "best_buy": 0,
      "best_sell": 0,
      "no_of_deals": 0,
      "daily_change": 0,
      "can_be_bought": true,
      "can_be_sold": true,
      "show_on_demo": true,
      "show_on_live": true,
      "use_ecn_fees": true
    },
    {
      "code": "DCCO",
      "name": "Deliverable Cocoa",
      "board": {
        "code": "S",
        "name": "Spot"
      },
      "board_code": "S",
      "commodity_code": "CCO",
      "location_basis_code": "",
      "created": "2021-10-04T05:10:01.932412Z",
      "commodity_image_url": "",
      "is_virtual_security": false,
      "volume_per_unit": 1000,
      "security_type": "Dawa",
      "season_to_date_change": 0,
      "best_buy": 0,
      "best_sell": 0,
      "no_of_deals": 0,
      "daily_change": 0,
      "can_be_bought": true,
      "can_be_sold": true,
      "show_on_demo": true,
      "show_on_live": true,
      "use_ecn_fees": true
    },
    {
      "code": "DSGM",
      "name": "Deliverable Sorghum",
      "board": {
        "code": "S",
        "name": "Spot"
      },
      "board_code": "S",
      "commodity_code": "SGM",
      "location_basis_code": "",
      "created": "2021-09-21T05:10:02.757788Z",
      "commodity_image_url": "/media/products/Soybean_UrbYV2U.jpeg",
      "is_virtual_security": false,
      "volume_per_unit": 1000,
      "security_type": "Dawa",
      "season_to_date_change": 0,
      "best_buy": 0,
      "best_sell": 0,
      "no_of_deals": 0,
      "daily_change": 0,
      "can_be_bought": true,
      "can_be_sold": true,
      "show_on_demo": true,
      "show_on_live": true,
      "use_ecn_fees": true
    },
    {
      "code": "DSSC",
      "name": "Deliverable Sesame Seed Cleaned",
      "board": {
        "code": "S",
        "name": "Spot"
      },
      "board_code": "S",
      "commodity_code": "SSC",
      "location_basis_code": "",
      "created": "2021-10-21T05:10:01.384863Z",
      "commodity_image_url": "",
      "is_virtual_security": false,
      "volume_per_unit": 1000,
      "security_type": "Dawa",
      "season_to_date_change": 0,
      "best_buy": 0,
      "best_sell": 0,
      "no_of_deals": 0,
      "daily_change": 0,
      "can_be_bought": true,
      "can_be_sold": true,
      "show_on_demo": true,
      "show_on_live": true,
      "use_ecn_fees": true
    }
  ]

  export default data